import React from 'react'
import Link from 'next/link'
import Head from 'next/head'

function logins() {
  return (
    <>

    
<Head>
        <title>Webspace - Login Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  <div className='h-[100vh] flex flex-col items-center justify-center'>
        <div className='flex flex-col items-center justify-center '>
            <div className='flex flex-col items-center justify-center mb-[20px]'>
            <h1 className='font-bold text-3xl text-[#043873] mb-[5px]'>
                Welcome back
            </h1>

            <p>Hey, team members should login to continue</p>

            </div>

            <div>
                <form>
                    <div style={{boxShadow:'-1px 100px 100px rgba(0,0,0,0.1)',borderRadius:'15px'}} className="mb-[20px]">
                        <input type="email" placeholder="info@gmail.com" className='border-2 border-[#FFE492] w-[300px] p-2 '/>
                    </div>
                    <div>
                        <input type="email" placeholder="info@gmail.com" className='border-2 border-[#FFE492] w-[300px] p-2 '/>
                    </div>
                    <div className='mt-[20px]'>
                       <button className='bg-[#043873] text-white w-[300px] p-2'>Login</button>
                    </div><br></br>
                    <div>
                        Members without an account?<Link href="signup">Sign up</Link> 
                    </div>
                </form>
            </div>


        </div>
    </div>
    
    </>
  )
}

export default logins